dataset:
  name: "MetaShift"
  path: &root_path "/home/yk449/datasets/MetaShift/Cat-Dog-indoor-outdoor/"
  stage: 'val'
  save_path: *root_path
 
concepts:
  names:
    - "Long snout"
    - "Short snout"
    - "Floppy ears"
    - "Upright ears"
    - "Round eyes"
    - "Slit pupils"
    - "Curled tail"
    - "Straight tail"
    - "Stocky body"
    - "Slim body"
    - "Wide muzzle"
    - "Narrow muzzle"
    - "Large nose"
    - "Small nose"
    - "Broad paws"
    - "Small paws"
    - "Short, dense fur"
    - "Fine, soft fur"
    - "Simple or spotted coat"
    - "Striped or marbled coat"
    - "Short whiskers"
    - "Long whiskers"
    - "Expressive face"
    - "Neutral face"
    - "Square or upright posture"
    - "Crouched or perched posture"

  mutuali_exclusive:
    - ["Long snout", "Short snout"]
    - ["Floppy ears", "Upright ears"]
    - ["Round eyes", "Slit pupils"]
    - ["Curled tail", "Straight tail"]
    - ["Stocky body", "Slim body"]
    - ["Wide muzzle", "Narrow muzzle"]
    - ["Large nose", "Small nose"]
    - ["Broad paws", "Small paws"]
    - ["Short, dense fur", "Fine, soft fur"]
    - ["Simple or spotted coat", "Striped or marbled coat"]
    - ["Short whiskers", "Long whiskers"]
    - ["Expressive face", "Neutral face"]
    - ["Square or upright posture", "Crouched or perched posture"]